import matplotlib.pyplot as plt
from adjacency_list_graph import AdjacencyListGraph
from dijkstra import dijkstra
#3 imports from the provided code libary that allow thos code to creat graphs with points and distences,
#provide a built in dijkstra algorithm function and allow us to create a histogram

vertices = ['Harrow & Wealdstone', 'Chalfont & Latimer', 'Chesham', 'Amersham', 'Chorleywood', 'Rickmansworth',
            'Kenton', 'Moor Park', 'Watford', 'Croxley', 'West Harrow', 'Harrow-on-the-Hill', 'North Harrow',
            'Pinner', 'Northwood Hills', 'Northwood', 'Northwick Park', 'Preston Road', 'South Kenton',
            'North Wembley', 'Wembley Central', 'Stonebridge Park', 'Harlesden', 'Willesden Junction',
            'Kensal Green', "Queen's Park", 'Kilburn Park', 'Maida Vale', 'Warwick Avenue', 'Paddington',
            'Edgware Road', 'Marylebone', 'Baker Street', "Regent's Park", 'Oxford Circus', 'Piccadilly Circus',
            'Charing Cross', 'Embankment', 'Waterloo', 'Lambeth North', 'Elephant & Castle', 'Epping',
            'Theydon Bois', 'Debden', 'Loughton', 'Buckhurst Hill', 'Woodford', 'South Woodford', 'Snaresbrook',
            'Roding Valley', 'Chigwell', 'Grange Hill', 'Hainault', 'Fairlop', 'Barkingside', 'Newbury Park',
            'Gants Hill', 'Redbridge', 'Wanstead', 'Leytonstone', 'Leyton', 'Stratford', 'Mile End',
            'Bethnal Green', 'Liverpool Street', 'Bank', "St. Paul's", 'Chancery Lane', 'Holborn', 'Tottenham',
            'Bond Street', 'Marble Arch', 'Lancaster Gate', 'Queensway', 'Notting Hill Gate', 'Holland Park',
            "Shepherd's Bush", 'White City', 'East Acton', 'North Acton', 'West Acton', 'Ealing Broadway',
            'Hanger Lane', 'Perivale', 'Greenford', 'Northolt', 'South Ruislip', 'Ruislip Gardens',
            'West Ruislip', 'Bayswater', 'High Street Kensington', 'Gloucester Road', 'South Kensington',
            'Sloane Square', 'Victoria', "St. James's Park", 'Westminster', 'Temple', 'Blackfriars',
            'Mansion House', 'Cannon Street', 'Monument', 'Tower Hill', 'Aldgate', 'Moorgate', 'Barbican',
            'Farringdon', "King's Cross St. Pancras", 'Euston Square', 'Great Portland Street', 'Royal Oak',
            'Westbourne Park', 'Ladbroke Grove', 'Latimer Road', 'Wood Lane', "Shepherd's Bush Market",
            'Goldhawk Road', 'Hammersmith', 'Upminster', 'Upminster Bridge', 'Hornchurch', 'Elm Park',
            'Dagenham East', 'Dagenham Heathway', 'Becontree', 'Upney', 'Barking', 'East Ham',
            'Upton Park', 'Plaistow', 'West Ham', 'Bromley-by-Bow', 'Bow Road', 'Stepney Green',
            'Whitechapel', 'Aldgate East', "Earl's Court", 'Kensington (Olympia)', 'West Brompton',
            'Fulham Broadway', 'Parsons Green', 'Putney Bridge', 'East Putney', 'Southfields', 'Wimbledon Park',
            'Wimbledon', 'West Kensington', 'Barons Court', 'Ravenscourt Park', 'Stamford Brook', 'Turnham Green',
            'Gunnersbury', 'Kew Gardens', 'Richmond', 'Chiswick Park', 'Acton Town', 'Ealing Common', 'Stanmore',
            'Canons Park', 'Queensbury', 'Kingsbury', 'Wembley Park', 'Neasden', 'Dollis Hill', 'Willesden Green',
            'Kilburn', 'West Hampstead', 'Finchley Road', 'Swiss Cottage', "St. John's Wood", 'Green Park',
            'Southwark', 'London Bridge', 'Bermondsey', 'Canada Water', 'Canary Wharf', 'North Greenwich',
            'Canning Town', 'High Barnet', 'Totteridge & Whetstone', 'Woodside Park', 'West Finchley',
            'Mill Hill East', 'Finchley Central', 'East Finchley', 'Highgate', 'Archway', 'Tufnell Park',
            'Kentish Town', 'Edgware', 'Burnt Oak', 'Colindale', 'Hendon Central', 'Brent Cross', 'Golders Green',
            'Hampstead', 'Belsize Park', 'Chalk Farm', 'Camden Town', 'Mornington Crescent', 'Warren Street',
            'Goodge Street', 'Tottenham Court Road', 'Leicester Square', 'Euston', 'Angel', 'Old Street',
            'Borough', 'Kennington', 'Oval', 'Clapham North', 'Clapham Common', 'Clapham South', 'Balham',
            'Tooting Bec', 'Tooting Broadway', 'Colliers Wood', 'South Wimbledon', 'Morden', 'Cockfosters',
            'Oakwood', 'Southgate', 'Arnos Grove', 'Bounds Green', 'Wood Green', 'Turnpike Lane', 'Manor House',
            'Finsbury Park Victoria', 'Arsenal', 'Holloway Road', 'Caledonian Road', 'Russell Square',
            'Holborn Central', 'Covent Garden', 'Hyde Park Corner', 'Knightsbridge', 'South Ealing',
            'Northfields', 'Boston Manor', 'Osterley', 'Hounslow East', 'Hounslow Central', 'Hounslow West',
            'Hatton Cross', 'Heathrow Terminals 1, 2, 3', 'Heathrow Terminal 5', 'Heathrow Terminal 4',
            'North Ealing', 'Park Royal', 'Alperton', 'Sudbury Town', 'Sudbury Hill', 'South Harrow',
            'Rayners Lane', 'Eastcote', 'Ruislip Manor', 'Ruislip', 'Ickenham', 'Hillingdon', 'Uxbridge',
            'Walthamstow Central', 'Blackhorse Road', 'Tottenham Hale', 'Seven Sisters', 'Finsbury Park',
            'Highbury & Islington', 'Pimlico', 'Vauxhall', 'Stockwell', 'Brixton','Nine Elms',
            'Battersea Power Station']
#vertices is defining each point on the graph we are going to make for this code, in this ccase it would be the
#station names


edges = [
    ("Harrow & Wealdstone", "Kenton", 2),
    ("Kenton", "South Kenton", 2),
    ("South Kenton", "North Wembley", 2),
    ("North Wembley", "Wembley Central", 2),
    ("Wembley Central", "Stonebridge Park", 2),
    ("Stonebridge Park", "Harlesden", 2),
    ("Harlesden", "Willesden Junction", 2),
    ("Willesden Junction", "Kensal Green", 3),
    ("Kensal Green", "Queen's Park", 2),
    ("Queen's Park", "Kilburn Park", 2),
    ("Kilburn Park", "Maida Vale", 2),
    ("Maida Vale", "Warwick Avenue", 1),
    ("Warwick Avenue", "Paddington", 2),
    ("Edgware Road", "Marylebone", 1),
    ("Marylebone", "Baker Street", 2),
    ("Baker Street", "Regent's Park", 2),
    ("Regent's Park", "Oxford Circus", 2),
    ("Oxford Circus", "Piccadilly Circus", 2),
    ("Piccadilly Circus", "Charing Cross", 2),
    ("Charing Cross", "Embankment", 1),
    ("Embankment", "Waterloo", 2),
    ("Waterloo", "Lambeth North", 2),
    ("Lambeth North", "Elephant & Castle", 3),
    ("Epping", "Theydon Bois", 3),
    ("Theydon Bois", "Debden", 3),
    ("Debden", "Loughton", 2),
    ("Loughton", "Buckhurst Hill", 3),
    ("Buckhurst Hill", "Woodford", 2),
    ("Woodford", "South Woodford", 3),
    ("South Woodford", "Snaresbrook", 2),
    ("Snaresbrook", "Leytonstone", 2),
    ("Roding Valley", "Woodford", 4),
    ("Roding Valley", "Chigwell", 3),
    ("Chigwell", "Grange Hill", 2),
    ("Grange Hill", "Hainault", 5),
    ("Hainault", "Fairlop", 2),
    ("Fairlop", "Barkingside", 2),
    ("Barkingside", "Newbury Park", 2),
    ("Newbury Park", "Gants Hill", 3),
    ("Gants Hill", "Redbridge", 2),
    ("Redbridge", "Wanstead", 2),
    ("Wanstead", "Leytonstone", 2),
    ("Leytonstone", "Leyton", 2),
    ("Leyton", "Stratford", 3),
    ("Stratford", "Mile End", 4),
    ("Mile End", "Bethnal Green", 2),
    ("Bethnal Green", "Liverpool Street", 3),
    ("Liverpool Street", "Bank", 2),
    ("Bank", "St. Paul's", 2),
    ("St. Paul's", "Chancery Lane", 2),
    ("Chancery Lane", "Holborn", 1),
    ("Holborn", "Tottenham", 2),
    ("Tottenham", "Oxford Circus", 1),
    ("Oxford Circus", "Bond Street", 2),
    ("Bond Street", "Marble Arch", 2),
    ("Marble Arch", "Lancaster Gate", 3),
    ("Lancaster Gate", "Queensway", 2),
    ("Queensway", "Notting Hill Gate", 2),
    ("Notting Hill Gate", "Holland Park", 1),
    ("Holland Park", "Shepherd's Bush", 2),
    ("Shepherd's Bush", "White City", 3),
    ("White City", "East Acton", 3),
    ("East Acton", "North Acton", 2),
    ("North Acton", "Hanger Lane", 3),
    ("North Acton", "West Acton", 2),
    ("West Acton", "Ealing Broadway", 3),
    ("Hanger Lane", "Perivale", 3),
    ("Perivale", "Greenford", 2),
    ("Greenford", "Northolt", 2),
    ("Northolt", "South Ruislip", 3),
    ("South Ruislip", "Ruislip Gardens", 2),
    ("Ruislip Gardens", "West Ruislip", 3),
    ("Paddington", "Bayswater", 2),
    ("Bayswater", "Notting Hill Gate", 2),
    ("Notting Hill Gate", "High Street Kensington", 2),
    ("High Street Kensington", "Gloucester Road", 3),
    ("Gloucester Road", "South Kensington", 3),
    ("South Kensington", "Sloane Square", 2),
    ("Sloane Square", "Victoria", 2),
    ("Victoria", "St. James's Park", 2),
    ("St. James's Park", "Westminster", 2),
    ("Westminster", "Embankment", 1),
    ("Embankment", "Temple", 2),
    ("Temple", "Blackfriars", 1),
    ("Blackfriars", "Mansion House", 2),
    ("Mansion House", "Cannon Street", 2),
    ("Cannon Street", "Monument", 1),
    ("Monument", "Tower Hill", 2),
    ("Tower Hill", "Aldgate", 2),
    ("Aldgate", "Liverpool Street", 3),
    ("Liverpool Street", "Moorgate", 2),
    ("Moorgate", "Barbican", 2),
    ("Barbican", "Farringdon", 1),
    ("Farringdon", "King's Cross St. Pancras", 4),
    ("King's Cross St. Pancras", "Euston Square", 2),
    ("Euston Square", "Great Portland Street", 2),
    ("Great Portland Street", "Baker Street", 2),
    ("Baker Street", "Edgware Road", 3),
    ("Paddington", "Royal Oak", 2),
    ("Royal Oak", "Westbourne Park", 2),
    ("Westbourne Park", "Ladbroke Grove", 2),
    ("Ladbroke Grove", "Latimer Road", 2),
    ("Latimer Road", "Wood Lane", 2),
    ("Wood Lane", "Shepherd's Bush Market", 2),
    ("Shepherd's Bush Market", "Goldhawk Road", 1),
    ("Goldhawk Road", "Hammersmith", 2),
    ("Upminster", "Upminster Bridge", 2),
    ("Upminster Bridge", "Hornchurch", 2),
    ("Hornchurch", "Elm Park", 2),
    ("Elm Park", "Dagenham East", 3),
    ("Dagenham East", "Dagenham Heathway", 2),
    ("Dagenham Heathway", "Becontree", 3),
    ("Becontree", "Upney", 2),
    ("Upney", "Barking", 3),
    ("Barking", "East Ham", 4),
    ("East Ham", "Upton Park", 2),
    ("Upton Park", "Plaistow", 2),
    ("Plaistow", "West Ham", 2),
    ("West Ham", "Bromley-by-Bow", 2),
    ("Bromley-by-Bow", "Bow Road", 2),
    ("Bow Road", "Mile End", 2),
    ("Mile End", "Stepney Green", 2),
    ("Stepney Green", "Whitechapel", 3),
    ("Whitechapel", "Aldgate East", 2),
    ("Aldgate East", "Tower Hill", 3),
    ("Tower Hill", "Monument", 2),
    ("Monument", "Cannon Street", 1),
    ("Cannon Street", "Mansion House", 2),
    ("Mansion House", "Blackfriars", 2),
    ("Blackfriars", "Temple", 1),
    ("Temple", "Embankment", 2),
    ("Embankment", "Westminster", 1),
    ("Westminster", "St. James's Park", 2),
    ("St. James's Park", "Victoria", 2),
    ("Victoria", "Sloane Square", 2),
    ("Sloane Square", "South Kensington", 2),
    ("Earl's Court", "Kensington (Olympia)", 3),
    ("Earl's Court", "High Street Kensington", 5),
    ("High Street Kensington", "Notting Hill Gate", 2),
    ("Notting Hill Gate", "Bayswater", 2),
    ("Earl's Court", "West Brompton", 2),
    ("West Brompton", "Fulham Broadway", 2),
    ("Fulham Broadway", "Parsons Green", 2),
    ("Parsons Green", "Putney Bridge", 3),
    ("Putney Bridge", "East Putney", 3),
    ("East Putney", "Southfields", 2),
    ("Southfields", "Wimbledon Park", 2),
    ("Wimbledon Park", "Wimbledon", 4),
    ("Earl's Court", "West Kensington", 2),
    ("West Kensington", "Barons Court", 2),
    ("Hammersmith", "Ravenscourt Park", 2),
    ("Ravenscourt Park", "Stamford Brook", 2),
    ("Stamford Brook", "Turnham Green", 1),
    ("Turnham Green", "Gunnersbury", 3),
    ("Gunnersbury", "Kew Gardens", 2),
    ("Kew Gardens", "Richmond", 4),
    ("Turnham Green", "Chiswick Park", 2),
    ("Chiswick Park", "Acton Town", 2),
    ("Ealing Common", "Ealing Broadway", 5),
    ("Stanmore", "Canons Park", 4),
    ("Canons Park", "Queensbury", 3),
    ("Queensbury", "Kingsbury", 2),
    ("Kingsbury", "Wembley Park", 3),
    ("Wembley Park", "Neasden", 4),
    ("Neasden", "Dollis Hill", 2),
    ("Dollis Hill", "Willesden Green", 2),
    ("Willesden Green", "Kilburn", 2),
    ("Kilburn", "West Hampstead", 2),
    ("West Hampstead", "Finchley Road", 1),
    ("Finchley Road", "Swiss Cottage", 2),
    ("Swiss Cottage", "St. John's Wood", 2),
    ("St. John's Wood", "Baker Street", 3),
    ("Baker Street", "Bond Street", 2),
    ("Bond Street", "Green Park", 2),
    ("Green Park", "Westminster", 2),
    ("Westminster", "Waterloo", 2),
    ("Waterloo", "Southwark", 2),
    ("Southwark", "London Bridge", 2),
    ("London Bridge", "Bermondsey", 2),
    ("Bermondsey", "Canada Water", 2),
    ("Canada Water", "Canary Wharf", 3),
    ("Canary Wharf", "North Greenwich", 3),
    ("North Greenwich", "Canning Town", 3),
    ("Canning Town", "West Ham", 3),
    ("West Ham", "Stratford", 2),
    ("Amersham", "Chalfont & Latimer", 4),
    ("Chesham", "Chalfont & Latimer", 9),
    ("Chalfont & Latimer", "Chorleywood", 4),
    ("Chorleywood", "Rickmansworth", 4),
    ("Rickmansworth", "Moor Park", 5),
    ("Watford", "Croxley", 4),
    ("Croxley", "Moor Park", 4),
    ("Uxbridge", "Hillingdon", 4),
    ("Hillingdon", "Ickenham", 2),
    ("Ickenham", "Ruislip", 2),
    ("Ruislip", "Ruislip Manor", 2),
    ("Ruislip Manor", "Eastcote", 2),
    ("Eastcote", "Rayners Lane", 2),
    ("Rayners Lane", "West Harrow", 3),
    ("West Harrow", "Harrow-on-the-Hill", 2),
    ("Harrow-on-the-Hill", "North Harrow", 3),
    ("North Harrow", "Pinner", 2),
    ("Pinner", "Northwood Hills", 3),
    ("Northwood Hills", "Northwood", 3),
    ("Northwood", "Moor Park", 3),
    ("Moor Park", "Harrow-on-the-Hill", 14),
    ("Harrow-on-the-Hill", "Finchley Road", 16),
    ("Harrow-on-the-Hill", "Wembley Park", 9),
    ("Harrow-on-the-Hill", "Northwick Park", 3),
    ("Northwick Park", "Preston Road", 3),
    ("Preston Road", "Wembley Park", 3),
    ("Wembley Park", "Finchley Road", 7),
    ("Finchley Road", "Baker Street", 5),
    ("Baker Street", "Great Portland Street", 2),
    ("Great Portland Street", "Euston Square", 2),
    ("Euston Square", "King's Cross St. Pancras", 2),
    ("King's Cross St. Pancras", "Farringdon", 2),
    ("Barbican", "Moorgate", 2),
    ("Moorgate", "Liverpool Street", 2),
    ("Liverpool Street", "Aldgate", 3),
    ("High Barnet", "Totteridge & Whetstone", 4),
    ("Totteridge & Whetstone", "Woodside Park", 2),
    ("Woodside Park", "West Finchley", 2),
    ("West Finchley", "Finchley Central", 2),
    ("Mill Hill East", "Finchley Central", 4),
    ("Finchley Central", "East Finchley", 4),
    ("East Finchley", "Highgate", 3),
    ("Highgate", "Archway", 3),
    ("Archway", "Tufnell Park", 2),
    ("Tufnell Park", "Kentish Town", 1),
    ("Kentish Town", "Camden Town", 2),
    ("Edgware", "Burnt Oak", 4),
    ("Burnt Oak", "Colindale", 2),
    ("Colindale", "Hendon Central", 3),
    ("Hendon Central", "Brent Cross", 2),
    ("Brent Cross", "Golders Green", 3),
    ("Golders Green", "Hampstead", 4),
    ("Hampstead", "Belsize Park", 3),
    ("Belsize Park", "Chalk Farm", 2),
    ("Chalk Farm", "Camden Town", 1),
    ("Camden Town", "Mornington Crescent", 2),
    ("Mornington Crescent", "Euston", 2),
    ("Warren Street", "Euston", 1),
    ("Warren Street", "Goodge Street", 2),
    ("Goodge Street", "Tottenham Court Road", 1),
    ("Tottenham Court Road", "Leicester Square", 2),
    ("Leicester Square", "Charing Cross", 1),
    ("Waterloo", "Kennington", 3),
    ("Euston", "Camden Town", 4),
    ("Euston", "King's Cross St. Pancras", 2),
    ("King's Cross St. Pancras", "Angel", 3),
    ("Angel", "Old Street", 3),
    ("Old Street", "Moorgate", 2),
    ("Moorgate", "Bank", 2),
    ("Bank", "London Bridge", 2),
    ("London Bridge", "Borough", 2),
    ("Borough", "Elephant & Castle", 2),
    ("Elephant & Castle", "Kennington", 2),
    ("Kennington", "Oval", 3),
    ("Oval", "Stockwell", 2),
    ("Stockwell", "Clapham North", 2),
    ("Clapham North", "Clapham Common", 2),
    ("Clapham Common", "Clapham South", 2),
    ("Clapham South", "Balham", 2),
    ("Balham", "Tooting Bec", 2),
    ("Tooting Bec", "Tooting Broadway", 2),
    ("Tooting Broadway", "Colliers Wood", 2),
    ("Colliers Wood", "South Wimbledon", 2),
    ("South Wimbledon", "Morden", 3),
    ("Cockfosters", "Oakwood", 2),
    ("Oakwood", "Southgate", 3),
    ("Southgate", "Arnos Grove", 4),
    ("Arnos Grove", "Bounds Green", 2),
    ("Bounds Green", "Wood Green", 3),
    ("Wood Green", "Turnpike Lane", 2),
    ("Turnpike Lane", "Manor House", 4),
    ("Manor House", "Finsbury Park Victoria", 2),
    ("Finsbury Park Victoria", "Arsenal", 1),
    ("Arsenal", "Holloway Road", 2),
    ("Holloway Road", "Caledonian Road", 2),
    ("Caledonian Road", "King's Cross St. Pancras", 4),
    ("King's Cross St. Pancras", "Russell Square", 2),
    ("Russell Square", "Holborn Central", 2),
    ("Holborn Central", "Covent Garden", 2),
    ("Covent Garden", "Leicester Square", 1),
    ("Leicester Square", "Piccadilly Circus", 1),
    ("Piccadilly Circus", "Green Park", 2),
    ("Green Park", "Hyde Park Corner", 2),
    ("Hyde Park Corner", "Knightsbridge", 2),
    ("Knightsbridge", "South Kensington", 2),
    ("South Kensington", "Gloucester Road", 2),
    ("Gloucester Road", "Earl's Court", 2),
    ("Earl's Court", "Barons Court", 3),
    ("Barons Court", "Hammersmith", 3),
    ("Hammersmith", "Acton Town", 8),
    ("Hammersmith", "Turnham Green", 4),
    ("Turnham Green", "Acton Town", 4),
    ("Acton Town", "South Ealing", 3),
    ("South Ealing", "Northfields", 1),
    ("Northfields", "Boston Manor", 2),
    ("Boston Manor", "Osterley", 3),
    ("Osterley", "Hounslow East", 2),
    ("Hounslow East", "Hounslow Central", 1),
    ("Hounslow Central", "Hounslow West", 3),
    ("Hounslow West", "Hatton Cross", 4),
    ("Hatton Cross", "Heathrow Terminals 1, 2, 3", 4),
    ("Heathrow Terminals 1, 2, 3", "Heathrow Terminal 5", 4),
    ("Hatton Cross", "Heathrow Terminal 4", 3),
    ("Acton Town", "Ealing Common", 2),
    ("Ealing Common", "North Ealing", 2),
    ("North Ealing", "Park Royal", 2),
    ("Park Royal", "Alperton", 2),
    ("Alperton", "Sudbury Town", 3),
    ("Sudbury Town", "Sudbury Hill", 2),
    ("Sudbury Hill", "South Harrow", 3),
    ("South Harrow", "Rayners Lane", 5),
    ("Rayners Lane", "Eastcote", 2),
    ("Eastcote", "Ruislip Manor", 2),
    ("Ruislip Manor", "Ruislip", 2),
    ("Ruislip", "Ickenham", 4),
    ("Ickenham", "Hillingdon", 2),
    ("Hillingdon", "Uxbridge", 4),
    ("Walthamstow Central", "Blackhorse Road", 3),
    ("Blackhorse Road", "Tottenham Hale", 3),
    ("Tottenham Hale", "Seven Sisters", 2),
    ("Seven Sisters", "Finsbury Park", 5),
    ("Finsbury Park", "Highbury & Islington", 2),
    ("Highbury & Islington", "King's Cross St. Pancras", 3),
    ("King's Cross St. Pancras", "Euston", 2),
    ("Euston", "Warren Street", 2),
    ("Warren Street", "Oxford Circus", 2),
    ("Oxford Circus", "Green Park", 2),
    ("Green Park", "Victoria", 2),
    ("Victoria", "Pimlico", 2),
    ("Pimlico", "Vauxhall", 2),
    ("Vauxhall", "Stockwell", 3),
    ("Stockwell", "Brixton", 2),
    ("Bank", "Waterloo", 5),
    ("Kenton", "Harrow & Wealdstone", 2),
    ("South Kenton", "Kenton", 2),
    ("North Wembley", "South Kenton", 2),
    ("Wembley Central", "North Wembley", 2),
    ("Stonebridge Park", "Wembley Central", 2),
    ("Harlesden", "Stonebridge Park", 2),
    ("Willesden Junction", "Harlesden", 2),
    ("Kensal Green", "Willesden Junction", 3),
    ("Queen's Park", "Kensal Green", 2),
    ("Kilburn Park", "Queen's Park", 2),
    ("Maida Vale", "Kilburn Park", 2),
    ("Warwick Avenue", "Maida Vale", 1),
    ("Paddington", "Warwick Avenue", 2),
    ("Edgware Road", "Paddington", 2),
    ("Marylebone", "Edgware Road", 1),
    ("Baker Street", "Marylebone", 2),
    ("Regent's Park", "Baker Street", 2),
    ("Oxford Circus", "Regent's Park", 2),
    ("Piccadilly Circus", "Oxford Circus", 2),
    ("Charing Cross", "Piccadilly Circus", 2),
    ("Lambeth North", "Waterloo", 2),
    ("Elephant & Castle", "Lambeth North", 3),
    ("Theydon Bois", "Epping", 3),
    ("Debden", "Theydon Bois", 3),
    ("Loughton", "Debden", 2),
    ("Buckhurst Hill", "Loughton", 3),
    ("Woodford", "Buckhurst Hill", 2),
    ("South Woodford", "Woodford", 3),
    ("Snaresbrook", "South Woodford", 2),
    ("Leytonstone", "Snaresbrook", 2),
    ("Woodford", "Roding Valley", 4),
    ("Chigwell", "Roding Valley", 3),
    ("Grange Hill", "Chigwell", 2),
    ("Hainault", "Grange Hill", 5),
    ("Fairlop", "Hainault", 2),
    ("Barkingside", "Fairlop", 2),
    ("Newbury Park", "Barkingside", 2),
    ("Gants Hill", "Newbury Park", 3),
    ("Redbridge", "Gants Hill", 2),
    ("Wanstead", "Redbridge", 2),
    ("Leytonstone", "Wanstead", 2),
    ("Leyton", "Leytonstone", 2),
    ("Stratford", "Leyton", 3),
    ("Mile End", "Stratford", 4),
    ("Bethnal Green", "Mile End", 2),
    ("Liverpool Street", "Bethnal Green", 3),
    ("Bank", "Liverpool Street", 2),
    ("St. Paul's", "Bank", 2),
    ("Chancery Lane", "St. Paul's", 2),
    ("Holborn", "Chancery Lane", 1),
    ("Tottenham", "Holborn", 2),
    ("Oxford Circus", "Tottenham", 1),
    ("Bond Street", "Oxford Circus", 2),
    ("Marble Arch", "Bond Street", 2),
    ("Lancaster Gate", "Marble Arch", 3),
    ("Queensway", "Lancaster Gate", 2),
    ("Notting Hill Gate", "Queensway", 2),
    ("Holland Park", "Notting Hill Gate", 1),
    ("Shepherd's Bush", "Holland Park", 2),
    ("White City", "Shepherd's Bush", 3),
    ("East Acton", "White City", 3),
    ("North Acton", "East Acton", 2),
    ("Hanger Lane", "North Acton", 3),
    ("West Acton", "North Acton", 2),
    ("Ealing Broadway", "West Acton", 3),
    ("Perivale", "Hanger Lane", 3),
    ("Greenford", "Perivale", 2),
    ("Northolt", "Greenford", 2),
    ("South Ruislip", "Northolt", 3),
    ("Ruislip Gardens", "South Ruislip", 2),
    ("West Ruislip", "Ruislip Gardens", 2),
    ("Paddington", "Edgware Road", 3),
    ("Bayswater", "Paddington", 2),
    ("Gloucester Road", "High Street Kensington", 3),
    ("Aldgate", "Tower Hill", 2),
    ("Farringdon", "Barbican", 1),
    ("Edgware Road", "Baker Street", 3),
    ("Royal Oak", "Paddington", 2),
    ("Westbourne Park", "Royal Oak", 2),
    ("Ladbroke Grove", "Westbourne Park", 2),
    ("Latimer Road", "Ladbroke Grove", 2),
    ("Wood Lane", "Latimer Road", 2),
    ("Shepherd's Bush Market", "Wood Lane", 2),
    ("Goldhawk Road", "Shepherd's Bush Market", 1),
    ("Hammersmith", "Goldhawk Road", 2),
    ("Upminster Bridge", "Upminster", 2),
    ("Hornchurch", "Upminster Bridge", 2),
    ("Elm Park", "Hornchurch", 2),
    ("Dagenham East", "Elm Park", 3),
    ("Dagenham Heathway", "Dagenham East", 2),
    ("Becontree", "Dagenham Heathway", 3),
    ("Upney", "Becontree", 2),
    ("Barking", "Upney", 3),
    ("East Ham", "Barking", 4),
    ("Upton Park", "East Ham", 2),
    ("Plaistow", "Upton Park", 2),
    ("West Ham", "Plaistow", 2),
    ("Bromley-by-Bow", "West Ham", 2),
    ("Bow Road", "Bromley-by-Bow", 2),
    ("Mile End", "Bow Road", 2),
    ("Stepney Green", "Mile End", 2),
    ("Whitechapel", "Stepney Green", 3),
    ("Aldgate East", "Whitechapel", 2),
    ("Tower Hill", "Aldgate East", 3),
    ("Earl's Court", "Gloucester Road", 2),
    ("Kensington (Olympia)", "Earl's Court", 3),
    ("High Street Kensington", "Earl's Court", 5),
    ("West Brompton", "Earl's Court", 2),
    ("Fulham Broadway", "West Brompton", 2),
    ("Parsons Green", "Fulham Broadway", 2),
    ("Putney Bridge", "Parsons Green", 3),
    ("East Putney", "Putney Bridge", 3),
    ("Southfields", "East Putney", 2),
    ("Wimbledon Park", "Southfields", 2),
    ("Wimbledon", "Wimbledon Park", 4),
    ("West Kensington", "Earl's Court", 2),
    ("Barons Court", "West Kensington", 2),
    ("Hammersmith", "Barons Court", 3),
    ("Ravenscourt Park", "Hammersmith", 2),
    ("Stamford Brook", "Ravenscourt Park", 2),
    ("Turnham Green", "Stamford Brook", 1),
    ("Gunnersbury", "Turnham Green", 3),
    ("Kew Gardens", "Gunnersbury", 2),
    ("Richmond", "Kew Gardens", 4),
    ("Chiswick Park", "Turnham Green", 2),
    ("Acton Town", "Chiswick Park", 2),
    ("Ealing Common", "Acton Town", 2),
    ("Ealing Broadway", "Ealing Common", 5),
    ("Liverpool Street", "Aldgate East", 3),
    ("Canons Park", "Stanmore", 4),
    ("Queensbury", "Canons Park", 3),
    ("Kingsbury", "Queensbury", 2),
    ("Wembley Park", "Kingsbury", 3),
    ("Neasden", "Wembley Park", 4),
    ("Dollis Hill", "Neasden", 2),
    ("Willesden Green", "Dollis Hill", 2),
    ("Kilburn", "Willesden Green", 2),
    ("West Hampstead", "Kilburn", 2),
    ("Finchley Road", "West Hampstead", 1),
    ("Swiss Cottage", "Finchley Road", 2),
    ("St. John's Wood", "Swiss Cottage", 2),
    ("Baker Street", "St. John's Wood", 3),
    ("Bond Street", "Baker Street", 2),
    ("Green Park", "Bond Street", 2),
    ("Westminster", "Green Park", 2),
    ("Waterloo", "Westminster", 2),
    ("Southwark", "Waterloo", 2),
    ("London Bridge", "Southwark", 2),
    ("Bermondsey", "London Bridge", 2),
    ("Canada Water", "Bermondsey", 2),
    ("Canary Wharf", "Canada Water", 3),
    ("North Greenwich", "Canary Wharf", 3),
    ("Canning Town", "North Greenwich", 3),
    ("Stratford", "West Ham", 2),
    ("Chalfont & Latimer", "Amersham", 4),
    ("Chalfont & Latimer", "Chesham", 9),
    ("Chorleywood", "Chalfont & Latimer", 4),
    ("Rickmansworth", "Chorleywood", 4),
    ("Moor Park", "Rickmansworth", 5),
    ("Croxley", "Watford", 4),
    ("Moor Park", "Croxley", 4),
    ("West Harrow", "Rayners Lane", 3),
    ("Harrow-on-the-Hill", "West Harrow", 2),
    ("North Harrow", "Harrow-on-the-Hill", 3),
    ("Pinner", "North Harrow", 2),
    ("Northwood Hills", "Pinner", 3),
    ("Northwood", "Northwood Hills", 3),
    ("Moor Park", "Northwood", 3),
    ("Harrow-on-the-Hill", "Moor Park", 14),
    ("Finchley Road", "Harrow-on-the-Hill", 16),
    ("Wembley Park", "Harrow-on-the-Hill", 9),
    ("Northwick Park", "Harrow-on-the-Hill", 3),
    ("Preston Road", "Northwick Park", 3),
    ("Wembley Park", "Preston Road", 3),
    ("Finchley Road", "Wembley Park", 7),
    ("Baker Street", "Finchley Road", 5),
    ("Totteridge & Whetstone", "High Barnet", 4),
    ("Woodside Park", "Totteridge & Whetstone", 2),
    ("West Finchley", "Woodside Park", 2),
    ("Finchley Central", "West Finchley", 2),
    ("Finchley Central", "Mill Hill East", 4),
    ("East Finchley", "Finchley Central", 4),
    ("Highgate", "East Finchley", 3),
    ("Archway", "Highgate", 3),
    ("Tufnell Park", "Archway", 2),
    ("Kentish Town", "Tufnell Park", 1),
    ("Camden Town", "Kentish Town", 2),
    ("Burnt Oak", "Edgware", 4),
    ("Colindale", "Burnt Oak", 2),
    ("Hendon Central", "Colindale", 3),
    ("Brent Cross", "Hendon Central", 2),
    ("Golders Green", "Brent Cross", 3),
    ("Hampstead", "Golders Green", 4),
    ("Belsize Park", "Hampstead", 3),
    ("Chalk Farm", "Belsize Park", 2),
    ("Camden Town", "Chalk Farm", 1),
    ("Mornington Crescent", "Camden Town", 2),
    ("Euston", "Mornington Crescent", 2),
    ("Goodge Street", "Warren Street", 2),
    ("Tottenham Court Road", "Goodge Street", 1),
    ("Leicester Square", "Tottenham Court Road", 2),
    ("Charing Cross", "Leicester Square", 1),
    ("Embankment", "Charing Cross", 1),
    ("Waterloo", "Embankment", 2),
    ("Kennington", "Waterloo", 3),
    ("Camden Town", "Euston", 4),
    ("Angel", "King's Cross St. Pancras", 3),
    ("Old Street", "Angel", 3),
    ("Moorgate", "Old Street", 2),
    ("Bank", "Moorgate", 2),
    ("London Bridge", "Bank", 2),
    ("Borough", "London Bridge", 2),
    ("Elephant & Castle", "Borough", 2),
    ("Kennington", "Elephant & Castle", 2),
    ("Oval", "Kennington", 3),
    ("Stockwell", "Oval", 2),
    ("Clapham North", "Stockwell", 2),
    ("Clapham Common", "Clapham North", 2),
    ("Clapham South", "Clapham Common", 2),
    ("Balham", "Clapham South", 2),
    ("Tooting Bec", "Balham", 2),
    ("Tooting Broadway", "Tooting Bec", 2),
    ("Colliers Wood", "Tooting Broadway", 2),
    ("South Wimbledon", "Colliers Wood", 2),
    ("Morden", "South Wimbledon", 3),
    ("Oakwood", "Cockfosters", 2),
    ("Southgate", "Oakwood", 3),
    ("Arnos Grove", "Southgate", 4),
    ("Bounds Green", "Arnos Grove", 2),
    ("Wood Green", "Bounds Green", 3),
    ("Turnpike Lane", "Wood Green", 2),
    ("Manor House", "Turnpike Lane", 4),
    ("Finsbury Park Victoria", "Manor House", 2),
    ("Arsenal", "Finsbury Park Victoria", 1),
    ("Holloway Road", "Arsenal", 2),
    ("Caledonian Road", "Holloway Road", 2),
    ("King's Cross St. Pancras", "Caledonian Road", 4),
    ("Russell Square", "King's Cross St. Pancras", 2),
    ("Holborn Central", "Russell Square", 2),
    ("Covent Garden", "Holborn Central", 2),
    ("Leicester Square", "Covent Garden", 1),
    ("Piccadilly Circus", "Leicester Square", 1),
    ("Green Park", "Piccadilly Circus", 2),
    ("Hyde Park Corner", "Green Park", 2),
    ("Knightsbridge", "Hyde Park Corner", 2),
    ("South Kensington", "Knightsbridge", 2),
    ("Barons Court", "Earl's Court", 3),
    ("Acton Town", "Hammersmith", 8),
    ("Turnham Green", "Hammersmith", 4),
    ("Acton Town", "Turnham Green", 4),
    ("South Ealing", "Acton Town", 3),
    ("Northfields", "South Ealing", 1),
    ("Boston Manor", "Northfields", 2),
    ("Osterley", "Boston Manor", 3),
    ("Hounslow East", "Osterley", 2),
    ("Hounslow Central", "Hounslow East", 1),
    ("Hounslow West", "Hounslow Central", 3),
    ("Hatton Cross", "Hounslow West", 4),
    ("Heathrow Terminals 1, 2, 3", "Hatton Cross", 4),
    ("Heathrow Terminal 5", "Heathrow Terminals 1, 2, 3", 4),
    ("Heathrow Terminal 4", "Hatton Cross", 3),
    ("North Ealing", "Ealing Common", 2),
    ("Park Royal", "North Ealing", 2),
    ("Alperton", "Park Royal", 2),
    ("Sudbury Town", "Alperton", 3),
    ("Sudbury Hill", "Sudbury Town", 2),
    ("South Harrow", "Sudbury Hill", 3),
    ("Rayners Lane", "South Harrow", 5),
    ("Blackhorse Road", "Walthamstow Central", 3),
    ("Tottenham Hale", "Blackhorse Road", 3),
    ("Seven Sisters", "Tottenham Hale", 2),
    ("Finsbury Park", "Seven Sisters", 5),
    ("Highbury & Islington", "Finsbury Park", 2),
    ("King's Cross St. Pancras", "Highbury & Islington", 3),
    ("Oxford Circus", "Warren Street", 2),
    ("Green Park", "Oxford Circus", 2),
    ("Victoria", "Green Park", 2),
    ("Pimlico", "Victoria", 2),
    ("Vauxhall", "Pimlico", 2),
    ("Stockwell", "Vauxhall", 3),
    ("Brixton", "Stockwell", 2),
    ("Waterloo", "Bank", 5)
]
#edges is also used when making the graph and works by adding ditence valuess between the vertices definded above 

def getEdgeTimes(start, end):
    for edge in edges:
        if (vertices[start] == edge[0] and vertices[end] == edge[1]) or (vertices[start] == edge[1] and vertices[end] == edge[0]):
            return edge[2]
#a callable function that gets the distence between two vertices using the edge values, made callable so it
#can be used multiple times within the same run of the program and return differnt values


def journeyPlanner():
        global timesList
        global d
        trainGraph = AdjacencyListGraph(len(vertices), True, True)
#this defines our stations graph using the pre provided AdjacencyListGraph code/modual to assign the nessary
#aguments to allow for the edges between vertices

        for edge in edges:
                trainGraph.insert_edge(vertices.index(edge[0]), vertices.index(edge[1]), edge[2])
#a for loop that for every value in edges (distences between two vertices) it will insert the edge tuple with all
#its values into the defined train graph
        
        d, pi = dijkstra(trainGraph, vertices.index(finish))
#definging two values by using the pre provided dijkstra taking two agunmentsn the graph with all station data
#and the value finish which is the input varible from the stat representing the usser desired desstination

        stationLists = [[] for _ in range(len(vertices))]
#defining a list that storess all the connecting verticies to the oringal giving verticy and one just for the times

        for i in range(len(pi)):
            if pi[i] is not None:
                currentStation = i
                while pi[currentStation] is not None:
                    lastStation = pi[currentStation]
                    stationLists[i].append("-> (" + str(getEdgeTimes(lastStation, currentStation)) + " mins)"" -> " + vertices[lastStation])
                    currentStation = lastStation
#this for loop is used for the output of the travaling stations between stops using a counter to run throught all
#the stations the journy takess to saves them line by line with the ssstation name and time to a lisst


        x = vertices.index(start)
        print(vertices[x] + ": total time of ("+ str(d[x]) + ") minuets, stations = ['"+vertices[x]+"'] "+ str(stationLists[x]))
#final overall output priting the starting station, the total time of the journy and the sstations list from before



while True:
        histogramData = []
        start = input("Starting Station: ")
        finish = input("End Station: " )
        journeyPlanner()
        for i in range(len(vertices)):
            histogramData.append(d[i])
        histogramData = [x for x in histogramData if x != float("inf")]     
        plt.xlabel('Time (Minuets)')
        plt.ylabel('Frequency')
        plt.title('Travel Times')
        plt.hist(histogramData, edgecolor='black')
        plt.show() 
#the starting input values that ask the user for thier starting station and thier desired destinaion, this
#value is used later in the actual logicn of the program plus a function to get the histogram data


